### ISSUE TITLE
`sort` method for Dataframe

### ISSUE THREAD

**Issue by sylwiabr** [luna/Dataframes#16]
### General Summary
We need to allow user sort the dataframe by values in column

### Motivation
It is a basic feature for a data library

### Specification
`Table.sort colNames ascending naPosition` - sort a values in dataframe. Returns new sorted dataframe.
`colNames` is a list of names to sort by; 
`ascending` Sort ascending vs. descending. Specify list for multiple sort orders. This is a list of bools, it must match the length of the `colNames`;
`naPosition` {‘first’, ‘last’}, default ‘last’, first puts NaNs at the beginning, last puts NaNs at the end

### Acceptance Criteria & Test Cases
Will be tested manually on large dataframes, by comparing the outputs with equivalent pandas operations.

**Comment by mwu-tow** [comment]
A few quick suggestions:
1) instead of passing two lists (colNames and ascending) I'd pass a single list of pairs -- that would enforce the matching lengths requirement on the interface level
2) instead of using Bools, there should be a class with `Ascending` and `Descending` constructors, so at the call place the intention is stated clearly
3) similarly use class/constructors as enum for `naPosition`
