### ISSUE TITLE
`toList` on Column is unsound

### ISSUE THREAD

**Issue by sylwiabr** [luna/dataframes#61]
While using the `Column.toList` we are completely breaking typechecker as it always results in a type of `[a...]` without checking any further constraints. This is really bad as it could easily unify with other types and in the best case return nonsense, while in the worst, crash everything. 

![bez nazwy](https://user-images.githubusercontent.com/12892578/46418629-7a59e400-c72c-11e8-8c97-2cf3a8dd112b.png)
![obraz](https://user-images.githubusercontent.com/12892578/46418798-c60c8d80-c72c-11e8-8408-3a7457d32879.png)

**Comment by kustosz** [comment]
The `toList` function is wrong and should report a TC error. I'll look into that over the weekend.

**Comment by wdanilo** [comment]
@kustosz what do you mean by that? Why should `toList` report an error and how it will be discovered?

The problem is that we don't encode the table layout on type-level now, so when you are converting a column to a list you cannot extract the information about the type, so for me, it seems the function `toList` is impossible to be written using current implementation, is that right? If so, I understand the only true solution here is to allow asap for type level parameters operations and using this information in functions like `toList`, while for now, we would have to force users to write something like `toIntList` or revert to list of dynamics, which is even worse.

**Comment by kustosz** [comment]
@wdanilo correct, this function should not be possible to write right now.

**Comment by mwu-tow** [comment]
When I observed this for the first time I filed https://github.com/luna/luna/issues/235  -- with a few additional variants of the issue that might worth checking when the TC is patched.

**Comment by mwu-tow** [comment]
Currently Dataframes `.toList` method relies on abusing this typechecker's behavior and I don't really see a clean alternative with current Luna typesystem. 
If TC closes the loophole, Dataframes will have to be adjusted as well. I haven't thought much about possible solutions but I have some fears that it will not be pretty.
It would be best, if we got more expressive typesystem / polymorphism mechanisms, allowing us to achieve code reuse without breaking TC.
