### ISSUE TITLE
Table.describe is very slow

### ISSUE THREAD

**Issue by wdanilo** [luna/Dataframes#70]
### General Summary

When using `Table.describe` on 90mb file is very slow. It takes 3 seconds in Python and 24 seconds in Luna. We need to investigate it further, probably it's connected with List iteration in interpreter, so we need to fix it together with @iamrecursion. For now, let's fix it in C++.

### Steps to Reproduce

See the benchmarks here: https://github.com/luna/benchmark-to-python/tree/master/1.describe
On Sylwia's Mac we've got `Python 3s` and `Luna ` 

### Luna Version

1.5.*

**Comment by mwu-tow** [comment]
Hard to say what gies wrong without proper investigation, likely many things together:
* CSV parsing is slow (when compared to pandas)
* describe makes multiple passes for each column (likely should gather many statistics for a column in a single pass)
* Luna lists are likely adding to this as well, though with 90 elements length this shouldn't be that bad just because of it

**Comment by mwu-tow** [comment]
The benchmark seems to require non-master branches both on Dataframes and Luna repo.

@wdanilo Are the times you give for describe or for read+describe?

**Comment by mwu-tow** [comment]
I run the quick and very rough test to compare performance on this file between Luna and Python:
|          | Luna   | Python |
|----------|--------|--------|
| read     | 2.72 s | 5.11 s |
| describe | 4.68 s | 0.9 s  |
| TOTAL    | 7.4 s  | 6.01 s |

While Luna is slower about 25% percent than Python in total, it certainly doesn't explain 8x difference that you are seeing. I run the test using shell Luna. Perhaps Luna Studio has some specific issues? (unfortunately I have no idea how the interpreter there can be profiled…)

**Comment by mwu-tow** [comment]
Naive C++ implementation should bring down describe time to about ~0.5 s — measuring on C++ side. Still, I have no idea what interpreter might end up doing, because the disparity between times we observe is too huge.  @sylwiabr Please also check that you have used Release mode Dataframes binaries (with optimizations enabled).

**Comment by sylwiabr** [comment]
Closing this one in favor of https://github.com/luna/Dataframes/issues/96
